//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storefront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int AlbumID { get; set; }
        public string AlbumTitle { get; set; }
        public string Description { get; set; }
        public int GenreID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public int RecordLabelID { get; set; }
        public string AlbumCover { get; set; }
        public int AlbumStatusID { get; set; }
        public int ArtistID { get; set; }
    
        public virtual AlbumStatus AlbumStatus { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual RecordLabel RecordLabel { get; set; }
    }
}
