//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storefront.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreFrontEntities : DbContext
    {
        public StoreFrontEntities()
            : base("name=StoreFrontEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albums> Albums1 { get; set; }
        public virtual DbSet<AlbumStatuses> AlbumStatuses { get; set; }
        public virtual DbSet<Artists> Artists1 { get; set; }
        public virtual DbSet<Departments> Departments1 { get; set; }
        public virtual DbSet<Employees> Employees1 { get; set; }
        public virtual DbSet<Genres> Genres1 { get; set; }
        public virtual DbSet<OtherProducts> OtherProducts1 { get; set; }
        public virtual DbSet<RecordLabels> RecordLabels1 { get; set; }
    }
}
